version: "3"
services:
    go:
        build: 
            context: .
            dockerfile: Dockerfile
        tty: true
        volumes:
            - ./:/go/src/github.com/gorogoroumaru/godb
        working_dir: /go/src/github.com/gorogoroumaru/godb
